### ISSUE TITLE
[suggestion] Allow to use $ in function names

### ISSUE THREAD

**Issue by OEvgeny** [stylecow/stylecow-core#2]
Is it possible to allow name function with $ sign? Like `$()` or `$myFunction()`?

**Comment by oscarotero** [comment]
The stylecow parser tries to match as much as possible to the css syntax.
According with the w3c spec, a function token is composed by `<ident-token> + (`, and an ident-token (the function name) must start by a letter, `-` or `_`. Any other character must be escaped, for example `\&`.

Here the info: https://drafts.csswg.org/css-syntax/#ident-token-diagram

So, for example `-fo()`, `--fo()`, `_fo()` or even `\(()` are allowed
but `123()` or `$()` not.

You can escape the dollar symbol `\$myFunction()` but I guess this is not what you want.
Other solution is use `_` for your custom functions, for example: `_()` or  `_myFunction()`

**Comment by OEvgeny** [comment]
@oscarotero thank you. Closing this. 

Stylecow is great!
