### ISSUE TITLE
Why do deno modules never actually work?

### ISSUE THREAD

**Issue by lawwantsin** [stylecow/stylecow-core#4]
While simply trying to run the example code.  I get.
```
error: Import 'https://deno.land/x/stylecow_color/mod.js' failed: 404 Not Found
error: Import 'https://deno.land/x/stylecow_prefixes/mod.js' failed: 404 Not Found
```
Which is because they don't exist.  Removing them from the example.  Just trying to get nested rules.  Which is all I wanted anyway.  I get:
```
warning: Compiled module not found "https://deno.land/std/testing/asserts.ts"
  From: https://deno.land/x/stylecow_core@v1.0.0/test.js
    If the source module contains only types, use `import type` and `export type` to import it instead.
error: Uncaught SyntaxError: The requested module 'https://deno.land/std/testing/asserts.ts' does not provide an export named 'assertEquals'
```
I mean.  Did you even bother to run the thing before you released it?
This after deno-sass failed miserably as well and is now archived.
Shame these libraries are dragging the whole Deno 1.0 momentum to the floor.

**Comment by oscarotero** [comment]
At this moment, only import and nested_rules plugins were ported to Deno (https://deno.land/x?query=stylecow)
The README example was inherited from the node version, so yes, it was wrong, sorry about that.
But if you use available plugins, it should work (I've used in my projects without problems).

The error with "https://deno.land/std/testing/asserts.ts" seems like you are using an old version. Try to reload the cache: `deno cache https://deno.land/std/testing/asserts.ts"` or better remove the entirely the cache folder.

FYI, I've contributed to port postcss to Deno (https://deno.land/x/postcss@8.1.4) that have a bigger community. There're no plugins available yet but you can import them from https://jspm.org/
Here you have an example:

- deps here: https://github.com/oscarotero/lume/blob/master/deps/postcss.js
- usage here: https://github.com/oscarotero/lume/blob/master/plugins/css.js#L3
